name: smartbuy
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  isar: ^3.1.0+1
  meta: ^1.9.1
  js: ^0.6.7
  ffi: ^2.1.0
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  animated_text_kit: ^4.2.2
  characters: ^1.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6


flutter:

  uses-material-design: true
  assets:
    - assets/images/splash.png
